services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - mysql-data:/var/lib/mysql

  auth:
    image: jangga/auth:latest

volumes:
  mysql-data:
