services:
  auth:
    image: jangga/auth:latest
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
