name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10

      - name: Install Auth Dependencies
        run: npm ci --prefix api/auth/
      - name: Install Account Dependencies
        run: npm ci --prefix api/account/

      - name: Run Auth Tests
        run: npm test --prefix api/auth/
      - name: Run Account Tests
        run: npm test --prefix api/account/
